---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-portal
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    revision: "{{ .Release.Revision }}"
    app.kubernetes.io/name: "{{ .Values.appName }}-portal"
spec:
  selector:
    matchLabels:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      app.kubernetes.io/name: "{{ .Values.appName }}-portal"
  replicas: {{ $.Values.portal.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      {{- if (eq (int $.Values.portal.replicaCount) 1) }}
      maxUnavailable: 0
      {{- else }}
      maxUnavailable: 1
      {{- end }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        app.kubernetes.io/name: "{{ .Values.appName }}-portal"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
                    release: {{ .Release.Name }}
                    heritage: {{ .Release.Service }}
                    app.kubernetes.io/name: "{{ .Values.appName }}-portal"
                topologyKey: kubernetes.io/hostname
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
                    release: {{ .Release.Name }}
                    heritage: {{ .Release.Service }}
                    app.kubernetes.io/name: "{{ .Values.appName }}-portal"
                topologyKey: topology.kubernetes.io/zone
      terminationGracePeriodSeconds: 10
      serviceAccountName: "{{ .Values.appName }}-service-account"
      containers:
        - name: portal
          image: {{ .Values.portal.image }}
          imagePullPolicy: {{ $.Values.portal.imagePullPolicy }}
          resources:
            requests:
              memory: {{ $.Values.portal.resources.requests.memory }}
              cpu: {{ $.Values.portal.resources.requests.cpu }}
            limits:
              memory: {{ $.Values.portal.resources.limits.memory }}
              cpu: {{ $.Values.portal.resources.limits.cpu }}
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(NODE_IP):4317
            - name: OTEL_EXPORTER_HEALTH_ENDPOINT
              value: http://$(NODE_IP):13133
            - name: SECRET_KEY
              value: "SECRET_KEY"
            - name: POSTGRES_ARCHITECTURE
              value: "{{ $.Values.postgresql.architecture }}"
            {{- if (eq $.Values.postgresql.architecture "standalone") }}
            - name: DATABASE_URL
              value: "postgresql://postgres:password@{{ $.Values.appName }}-postgresql/myapp"
            {{- else }}
            - name: DATABASE_URL
              value: "postgresql://postgres:password@{{ $.Values.appName }}-postgresql-primary/myapp"
            {{- end }}
            - name: REDIS_HOST
              value: "{{ $.Values.appName }}-redis-master"
            - name: SCOREBOARD_HOST
              value: "{{ $.Values.appName }}-scoreboard"
            - name: OTEL_SERVICE_NAME
              value: "{{ $.Values.appName }}-portal"
            - name: OTEL_ENVIRONMENT
              value: "{{ index $.Values "splunk-otel-collector" "environment" }}"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=$(OTEL_SERVICE_NAME),service.namespace={{ .Release.Namespace }},deployment.environment=$(OTEL_ENVIRONMENT)"
            - name: SPLUNK_OBSERVABILITY_REALM
              value: "{{ index $.Values "splunk-otel-collector" "splunkObservability" "realm" }}"
            - name: SPLUNK_OBSERVABILITY_API_ACCESS_TOKEN
              value: "{{ $.Values.observabilityApiAccessToken }}"
            - name: PLAYER_CABINET_IMAGE
              value: "{{ $.Values.cabinet.image }}"
            # for pull we'll just do whatever cabinet is (even for the cloud job)
            - name: IMAGE_PULL_POLICY
              value: "{{ $.Values.cabinet.imagePullPolicy }}"
            - name: ARCADE_HOST
              value: "{{ $.Values.arcadeHost }}"
            - name: OPENAI_API_KEY
              value: "{{ $.Values.openaiApiKey }}"
          ports:
            - name: http
              containerPort: 5000
          readinessProbe:
            httpGet:
              path: /alive
              port: http
              scheme: HTTP
            successThreshold: 1
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /alive
              port: http
              scheme: HTTP
            successThreshold: 1
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 5