---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.appName }}-portal
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    revision: "{{ .Release.Revision }}"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.appName }}-service-account"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: "{{ .Values.appName }}-portal"
  apiGroup: rbac.authorization.k8s.io